[package]
name = "rust-bert"
version = "0.7.3"
authors = ["Guillaume Becquin <guillaume.becquin@gmail.com>"]
edition = "2018"
description = "Ready-to-use NLP pipelines and transformer-based models (BERT, DistilBERT, GPT2,...)"
repository = "https://github.com/guillaume-be/rust-bert"
documentation = "https://docs.rs/rust-bert"
license = "Apache-2.0"
readme = "README.md"
keywords = ["nlp", "deep-learning", "machine-learning", "bert", "transformers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_bert"
path = "src/lib.rs"
crate-type = ["lib"]

[[bin]]
name = "convert-tensor"
path = "src/convert-tensor.rs"
doc = false

[features]
doc-only = ["tch/doc-only"]
all-tests = []

[package.metadata.docs.rs]
features = [ "doc-only" ]

[dependencies]
rust_tokenizers = "~3.0.0"
tch = "~0.1.7"
serde_json = "1.0.51"
serde = {version = "1.0.106", features = ["derive"]}
failure = "0.1.7"
dirs = "2.0.0"
itertools = "0.9.0"
ordered-float = "1.0.2"
csv = "1.1.3"
reqwest = "0.10.4"
lazy_static = "1.4.0"
tokio = { version = "0.2.19", features = ["full"] }